//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RB2017.articles.sending_a_html_and_plain_text_e_newsletter_asp_net_part_2 {
    
    
    public partial class _default {
    }
}
