//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RB2017.articles.creating_a_asp_net_registration_and_confirmation_system
{


	public partial class _default
	{
	}
}
