//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RB2017.articles.creating_a_web_based_schedule_asp_net_ms_sql_server
{


	public partial class default6
	{
	}
}
